### ISSUE TITLE
Can't see submit button in mobile view. 

### ISSUE THREAD

**Issue by simmimourya1** [ClusterInnovationCentre/register#2]

**Comment by devkhan** [comment]
Are the buttons disabled or invisible/inaccessible?

I can see it just fine, can you provide a screenshot?

**Comment by simmimourya1** [comment]
Screeshots. 
![screenshot_2016-08-31-00-18-23](https://cloud.githubusercontent.com/assets/8150326/18102658/f2da96c0-6f10-11e6-83b4-75db0549d690.png)
![screenshot_2016-08-31-00-19-06]
(https://cloud.githubusercontent.com/assets/8150326/18102679/06913dea-6f11-11e6-8601-707f124e73c5.png)

**Comment by devkhan** [comment]
These are actually disabled until you enter information in the required fields. This is desired behaviour, closing now.
